### ISSUE TITLE
Readme would be awesome 

### ISSUE THREAD

**Issue by johntdyer** [terafin/homeautomation-js-lib#4]
so I am trying to use the unifi-protect bridge and I am trying to understand how to use a config.yaml file which I think is supported w/ this library.  I am hoping you can point me in the right direction.  Thanks !

**Comment by terafin** [comment]
Hi there, I just added a readme for the unifi protect bridge:
https://github.com/terafin/mqtt-unifi-protect-bridge/blob/master/README.md

Let me know if that doesn't work for you!

**Comment by johntdyer** [comment]
Thank you very much!

**Comment by terafin** [comment]
Very welcome!
